image: verhulstm/circleci-ubuntu1804:0.0.5

full-build:
  script:
    - sudo bash .gitlabci/mock_vagrant.sh
    - cd /vagrant; sudo bash .gitlabci/download_python_environment_manager.sh
    - cd /vagrant; sudo su -c "sudo make linux" vagrant
